### ISSUE TITLE
Github folder structure.... why? 

### ISSUE THREAD

**Issue by kragnoth** [John-Smith-Modded/JSTR-Modded-1.7.x#182]
Please consider changing the structure to be assets -> mod name, instead of modname -> assets -> mod name.  It would make it much easier to grab the whole thing and dump into a texture pack.  The way it is by default might work in linux with a bash command, but it is a bit of a PITA to fix in windows without going through every folder and cutting/pasting the folder.

**Comment by artdude543** [comment]
The current structure for the repo is designed to make it easy for backend scripts/services to create downloads on the fly. These are the ones you find on Curse and/or CDN's. I can understand that making one yourself via the repo is a pain but it's not the recommended method for getting the pack as a download.

Downloads are outdated on Curse due to a few issues (which are on my hand) but are being fixed soon hopefully.

But ideally, we'd recommend getting the downloads from Curse.

**Comment by ScottKillen** [comment]
One of the issues is that some mods change assets in other places. Some change Minecraft's or other mod's resources and some do not follow the recommended folder structure... 

On another note, if you have a bash script that works, [Windows now has native support for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by damonmensch** [comment]
Please see the attached release in the mean time while curse gets updated. https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/releases/latest
